// 서비스워커: 버전별 앱 셸 사전 캐시(화면·모듈을 한 스냅샷으로 제공) + 글꼴 조각은 사용할 때 캐시
// 새 배포는 REVISION 이 바뀌어 설치되고 대기 → 화면(js/ui/pwa.js)이 SKIP_WAITING 을 보내면 곧바로 적용됨(작업 중이 아니면 자동, 작업 중이면 저장 후)
// 화면과의 약속: SKIP_WAITING(대기 중인 워커 활성화), GET_VERSION(MessagePort 로 {version, revision} 응답)
// 아래 생성 블록은 tools/build-sw.mjs 가 만듭니다 — 직접 고치지 마세요(tests/static/pwa.test.js 가 최신 여부 검사)
// <generated by tools/build-sw.mjs>
const VERSION = "5.47.10";
const REVISION = "bfcb533ba6245e7e";
const ASSETS = [
  "css/app.css",
  "css/present.css",
  "icons/apple-touch-icon.png",
  "icons/favicon-16.png",
  "icons/favicon-32.png",
  "icons/favicon-48.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon-maskable.svg",
  "icons/icon.svg",
  "index.html",
  "js/admin/access.js",
  "js/admin/feature-status.js",
  "js/admin/flags-client.js",
  "js/admin/releases.js",
  "js/analysis/cross.js",
  "js/analysis/items.js",
  "js/analysis/prepost.js",
  "js/analysis/representativeness.js",
  "js/analysis/run.js",
  "js/analysis/text.js",
  "js/auth/api.js",
  "js/auth/session.js",
  "js/boot-check.js",
  "js/charts/rasterize.js",
  "js/charts/svg.js",
  "js/charts/theme.js",
  "js/core/util.js",
  "js/evaluation/business-doc.js",
  "js/evaluation/business-sheet.js",
  "js/evaluation/instrument.js",
  "js/evaluation/kpi.js",
  "js/evaluation/linkage.js",
  "js/evaluation/logic-model.js",
  "js/evaluation/measurement-quality.js",
  "js/evaluation/measurement-results.js",
  "js/evaluation/pair-quality.js",
  "js/evaluation/reference-evidence.js",
  "js/history/crypto.js",
  "js/history/snapshot.js",
  "js/history/undo.js",
  "js/io/parse.js",
  "js/io/project.js",
  "js/io/template-xlsx.js",
  "js/main.js",
  "js/model/codebook.js",
  "js/model/detect.js",
  "js/model/label-sets.js",
  "js/model/prepost.js",
  "js/model/recode.js",
  "js/model/survey.js",
  "js/model/year-bucket.js",
  "js/narrative/josa.js",
  "js/narrative/vocab.js",
  "js/present/deck.js",
  "js/present/edit/detach.js",
  "js/present/edit/keys.js",
  "js/present/edit/render-custom.js",
  "js/present/edit/scroll-fit.js",
  "js/present/export-html.js",
  "js/report/build-report.js",
  "js/report/hwpx/fonts.js",
  "js/report/hwpx/metrics.js",
  "js/report/hwpx/package.js",
  "js/report/hwpx/read.js",
  "js/report/hwpx/symbols.js",
  "js/report/hwpx/template-parts.js",
  "js/report/hwpx/validate.js",
  "js/report/hwpx/writer.js",
  "js/report/hwpx/xml.js",
  "js/report/inline-marks.js",
  "js/report/model.js",
  "js/report/pptx/emu.js",
  "js/report/pptx/package.js",
  "js/report/pptx/template-parts.js",
  "js/report/pptx/validate.js",
  "js/report/pptx/writer.js",
  "js/report/pptx/xml.js",
  "js/report/render-html.js",
  "js/report/render-hwpx.js",
  "js/report/render-pptx.js",
  "js/stats/adjust.js",
  "js/stats/anova.js",
  "js/stats/categorical.js",
  "js/stats/correlation.js",
  "js/stats/descriptive.js",
  "js/stats/distributions.js",
  "js/stats/effectsize.js",
  "js/stats/nonparametric.js",
  "js/stats/normality.js",
  "js/stats/posthoc.js",
  "js/stats/regression.js",
  "js/stats/reliability.js",
  "js/stats/ttest.js",
  "js/telemetry/track.js",
  "js/ui/examples.js",
  "js/ui/fontcheck.js",
  "js/ui/format-toolbar.js",
  "js/ui/history/db.js",
  "js/ui/history/manager.js",
  "js/ui/history/version.js",
  "js/ui/icons.js",
  "js/ui/inline-edit.js",
  "js/ui/jszip-loader.js",
  "js/ui/kpi-cards.js",
  "js/ui/load-motion.js",
  "js/ui/measurement-workbench.js",
  "js/ui/present-canvas.js",
  "js/ui/present-edit-model.js",
  "js/ui/press-guard.js",
  "js/ui/pwa.js",
  "js/ui/router.js",
  "js/ui/sample-glyphs.js",
  "js/ui/score-basis.js",
  "js/ui/scrollhint.js",
  "js/ui/sticky-thead.js",
  "js/ui/store.js",
  "js/ui/theme.js",
  "js/ui/tooltip.js",
  "js/ui/tutorial.js",
  "js/ui/update-banner.js",
  "js/ui/update-policy.js",
  "js/ui/util.js",
  "js/ui/views/admin.js",
  "js/ui/views/admin/content.js",
  "js/ui/views/admin/flags.js",
  "js/ui/views/admin/stats-advanced.js",
  "js/ui/views/admin/stats.js",
  "js/ui/views/admin/users.js",
  "js/ui/views/business.js",
  "js/ui/views/dash.js",
  "js/ui/views/history.js",
  "js/ui/views/load.js",
  "js/ui/views/login.js",
  "js/ui/views/present-edit.js",
  "js/ui/views/present.js",
  "js/ui/views/references.js",
  "js/ui/views/report.js",
  "js/ui/views/settings.js",
  "js/ui/views/setup.js",
  "js/ui/views/updates.js",
  "js/ui/xlsx-loader.js",
  "manifest.webmanifest",
  "samples/2026_%EB%A6%AC%EB%8D%94%EC%8B%AD%EC%BA%A0%ED%94%84_%EC%82%AC%EC%A0%84%EC%82%AC%ED%9B%84_%ED%95%9C%EC%8B%9C%ED%8A%B8.xlsx",
  "samples/2026_%EC%83%9D%ED%83%9C%ED%83%90%ED%97%98_7%EC%A0%90%EC%B2%99%EB%8F%84_NPS.xlsx",
  "samples/2026_%EC%A7%84%EB%A1%9C%EC%B2%B4%ED%97%98_%EB%84%A4%EC%9D%B4%EB%B2%84%ED%8F%BC.csv",
  "samples/2026_%EC%A7%84%EB%A1%9C%ED%83%90%EC%83%89_%EC%82%AC%EC%A0%84%EC%82%AC%ED%9B%84.xlsx",
  "samples/2026_%EC%B0%B8%EC%97%AC%EC%9C%84%EC%9B%90%ED%9A%8C_%ED%9A%8C%EA%B3%A0%EC%8B%9D.xlsx",
  "samples/2026_%EC%B2%AD%EC%86%8C%EB%85%84%EC%84%BC%ED%84%B0_%EB%A7%8C%EC%A1%B1%EB%8F%84_%EA%B5%AC%EA%B8%80%ED%8F%BC.csv",
  "vendor/fonts/pretendard-gov/pretendard-gov-dynamic-subset.css",
  "vendor/jszip-3.10.1.min.js",
  "vendor/papaparse-5.4.1.min.js",
  "vendor/xlsx-0.20.3.full.min.js"
];
// </generated>

const SHELL = `survey-shell-${VERSION}-${REVISION}`;
const FONTS = "survey-fonts-pretendard-gov-1.3.9";
const SCOPE = new URL(self.registration.scope);
const INDEX = new URL("index.html", SCOPE).href;

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // 리비전을 쿼리로 붙여 받는다: 배포 직후 CDN·HTTP 캐시가 예전 파일을 내주더라도 이번 배포본을 확실히 받음 (조회할 때는 쿼리 무시)
    await cache.addAll(ASSETS.map(a => new Request(`${new URL(a, SCOPE).href}?r=${REVISION}`, { cache: "reload" })));
    // 배포가 덜 퍼져 index.html 이 예전 것이면(?v= 가 이 워커의 VERSION 과 다름) 설치 실패로 두고 다음 확인 때 다시 시도 — 엇갈린 스냅샷을 굳히지 않음
    const html = await (await cache.match(INDEX, { ignoreSearch: true }))?.text();
    if (!html || !html.includes(`?v=${VERSION}`)) { await caches.delete(SHELL); throw new Error("index.html 이 이 버전과 맞지 않음"); }
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith("survey-shell-") && k !== SHELL).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", event => {
  const type = event.data?.type;
  if (type === "SKIP_WAITING") self.skipWaiting();
  else if (type === "GET_VERSION") event.ports[0]?.postMessage({ version: VERSION, revision: REVISION });
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== SCOPE.origin || !url.pathname.startsWith(SCOPE.pathname)) return;
  if (url.pathname === new URL("sw.js", SCOPE).pathname) return; // 새 버전 확인용 sw.js 는 캐시를 거치지 않고 항상 네트워크로
  if (req.mode === "navigate") event.respondWith(page(req, url));
  else if (url.pathname.includes("/vendor/fonts/")) event.respondWith(fontFirst(req));
  else event.respondWith(shellFirst(req));
});

/** 앱 화면(index)은 사전 캐시본으로 즉시 표시, 그 밖의 페이지(legacy 등)는 네트워크 우선 */
async function page(req, url) {
  const isApp = url.pathname === SCOPE.pathname || url.pathname === new URL(INDEX).pathname;
  if (isApp) {
    const hit = await caches.match(INDEX, { cacheName: SHELL, ignoreSearch: true });
    if (hit) return hit;
  }
  try {
    return await fetch(req);
  } catch (err) {
    const fallback = await caches.match(INDEX, { cacheName: SHELL, ignoreSearch: true });
    if (fallback) return fallback;
    throw err;
  }
}

/** 버전 스냅샷에 있으면 캐시(쿼리 ?v= 무시), 없으면 네트워크 */
async function shellFirst(req) {
  const hit = await caches.match(req, { cacheName: SHELL, ignoreSearch: true });
  return hit || fetch(req);
}

/** 글꼴 조각: 한 번 받은 것은 계속 캐시 사용 (경로에 글꼴 버전 고정) */
async function fontFirst(req) {
  const cache = await caches.open(FONTS);
  const hit = await cache.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) cache.put(req, res.clone());
  return res;
}
