// 앱 업데이트 판단 규칙 (Node — 시계는 인자로 주입)
import test from "node:test";
import assert from "node:assert/strict";
import {
  DEFAULTS, parseVersion, compareVersions, parseSwVersion, releaseKey, detectUpdate, pageIsStale, nextCheckDelay, shouldCheck, checkWaitMs,
  snoozeUntil, isSnoozed, shouldShowBanner, unsafeReason, canAutoApply, bannerCopy, readGuard, recordReload, autoReloadAllowed, parseResume,
} from "../../js/ui/update-policy.js";

const T0 = 1_000_000;

// ───────────── 버전 ─────────────
test("parseVersion: 숫자·점만, 2~4 마디", () => {
  assert.deepEqual(parseVersion("5.28.0"), [5, 28, 0]);
  assert.deepEqual(parseVersion(" 5.28 "), [5, 28]);
  for (const bad of ["", "5", "v5.28.0", "5.28.0-beta", "5..0", "a.b.c", "1.2.3.4.5", null, undefined, 5.28, "5.28.0\n; drop"]) assert.equal(parseVersion(bad), null, String(bad));
});

test("compareVersions: 크기 순서·마디 수 차이·해석 불가", () => {
  assert.equal(compareVersions("5.28.0", "5.28.0"), 0);
  assert.equal(compareVersions("5.29.0", "5.28.9"), 1);
  assert.equal(compareVersions("5.9.0", "5.28.0"), -1, "문자열이 아니라 숫자 비교");
  assert.equal(compareVersions("6.0.0", "5.99.99"), 1);
  assert.equal(compareVersions("5.28", "5.28.0"), 0);
  assert.equal(compareVersions("5.28.1", "5.28"), 1);
  assert.equal(compareVersions("x", "5.28.0"), null);
  assert.equal(compareVersions("5.28.0", undefined), null);
});

// ───────────── sw.js 원문 파싱 ─────────────
const SW = `// 서비스워커\n// <generated by tools/build-sw.mjs>\nconst VERSION = "5.29.1";\nconst REVISION = "ABCDEF0123456789";\nconst ASSETS = [];\n// </generated>\nconst SHELL = \`x\`;`;

test("parseSwVersion: 정상 sw.js 에서 버전·리비전(소문자화)", () => {
  assert.deepEqual(parseSwVersion(SW), { version: "5.29.1", revision: "abcdef0123456789" });
  assert.deepEqual(parseSwVersion(SW.replace(/\n/g, "\r\n")), { version: "5.29.1", revision: "abcdef0123456789" }, "CRLF 도 허용");
});

test("parseSwVersion: 리비전이 없거나 이상해도 버전만 있으면 통과", () => {
  assert.deepEqual(parseSwVersion('const VERSION = "5.30.0";'), { version: "5.30.0", revision: null });
  assert.deepEqual(parseSwVersion('const VERSION = "5.30.0";\nconst REVISION = "xyz!";'), { version: "5.30.0", revision: null });
});

test("parseSwVersion: 깨진 원문·오류 페이지·빈 응답·형식 변경은 null", () => {
  for (const bad of ["", null, undefined, 42, "<!doctype html><title>404</title>", "const REVISION = \"abcdef0123\";", 'const VERSION = "";', 'const VERSION = "latest";', "const VERSION = '5.28.0';", 'var VERSION = "5.28.0"', "// const VERSION = \"5.28.0\"", 'const VERSION = "5.28.0'])
    assert.equal(parseSwVersion(bad), null, String(bad).slice(0, 40));
});

test("parseSwVersion: 매우 큰 응답도 앞부분만 보고 빠르게 처리", () => {
  const big = `${SW}\n${"x".repeat(5_000_000)}`;
  assert.equal(parseSwVersion(big).version, "5.29.1");
  assert.equal(parseSwVersion(`${"y".repeat(30_000)}\nconst VERSION = "5.29.1";`), null, "앞 20KB 밖은 무시");
});

test("releaseKey: 버전+리비전, 정보 없으면 빈 문자열", () => {
  assert.equal(releaseKey({ version: "5.29.0", revision: "ab12cd" }), "5.29.0#ab12cd");
  assert.equal(releaseKey({ version: "5.29.0", revision: null }), "5.29.0#");
  assert.equal(releaseKey(null), "");
  assert.equal(releaseKey({}), "");
});

// ───────────── 업데이트 감지 ─────────────
test("detectUpdate: 더 높은 버전은 업데이트", () => {
  const d = detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, { version: "5.29.0", revision: "bbbbbb" });
  assert.deepEqual(d, { available: true, reason: "newer", version: "5.29.0" });
});

test("detectUpdate: 같은 버전·같은 리비전은 업데이트 아님", () => {
  assert.equal(detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, { version: "5.28.0", revision: "aaaaaa" }).available, false);
  assert.equal(detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, { version: "5.28.0", revision: "aaaaaa" }).reason, "same");
});

test("detectUpdate: 같은 버전이라도 리비전이 다르면(버전을 올리지 않은 배포) 업데이트", () => {
  const d = detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, { version: "5.28.0", revision: "bbbbbb" });
  assert.equal(d.available, true);
  assert.equal(d.reason, "revision");
});

test("detectUpdate: 실행 중 리비전을 모르면(예전 서비스워커·첫 방문) 같은 버전은 업데이트 아님", () => {
  assert.equal(detectUpdate({ version: "5.28.0", revision: null }, { version: "5.28.0", revision: "bbbbbb" }).available, false);
  assert.equal(detectUpdate({ version: "5.28.0" }, { version: "5.28.0", revision: null }).available, false);
});

test("detectUpdate: 서버가 더 낮은 버전(오래된 CDN 사본·롤백)은 여기서 업데이트로 보지 않음", () => {
  const d = detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, { version: "5.27.0", revision: "cccccc" });
  assert.deepEqual(d, { available: false, reason: "older", version: "5.27.0" });
});

test("detectUpdate: 원격 정보 없음·형식 오류는 조용히 '알 수 없음'", () => {
  for (const remote of [null, undefined, {}, { version: "" }, { version: "abc" }, { version: null, revision: "aa" }])
    assert.equal(detectUpdate({ version: "5.28.0", revision: "aaaaaa" }, remote).available, false);
  assert.equal(detectUpdate({ version: "??" }, { version: "5.28.0" }).available, false, "실행 버전이 이상해도 오탐하지 않음");
});

test("detectUpdate: 파싱한 sw.js 와 곧바로 연결", () => {
  const remote = parseSwVersion(SW);
  assert.equal(detectUpdate({ version: "5.28.0", revision: "0000000000000000" }, remote).available, true);
  assert.equal(detectUpdate({ version: "5.29.1", revision: "abcdef0123456789" }, remote).available, false);
});

test("pageIsStale: 활성 서비스워커가 화면보다 새 버전일 때만", () => {
  assert.equal(pageIsStale("5.28.0", { version: "5.29.0" }), true);
  assert.equal(pageIsStale("5.28.0", { version: "5.28.0" }), false);
  assert.equal(pageIsStale("5.29.0", { version: "5.28.0" }), false);
  assert.equal(pageIsStale("5.28.0", null), false);
  assert.equal(pageIsStale("5.28.0", { version: "?" }), false);
});

// ───────────── 확인 주기 ─────────────
test("nextCheckDelay: 보이는 동안 60초, 실패마다 2배(상한 5분), 숨김이면 null", () => {
  assert.equal(nextCheckDelay({}), 60_000);
  assert.equal(nextCheckDelay({ failures: 1 }), 120_000);
  assert.equal(nextCheckDelay({ failures: 2 }), 240_000);
  assert.equal(nextCheckDelay({ failures: 3 }), 300_000);
  assert.equal(nextCheckDelay({ failures: 999 }), 300_000);
  assert.equal(nextCheckDelay({ failures: -4 }), 60_000);
  assert.equal(nextCheckDelay({ failures: Number.NaN }), 60_000);
  assert.equal(nextCheckDelay({ hidden: true }), null);
  assert.equal(nextCheckDelay({ failures: 1, pollMs: 1000, maxBackoffMs: 1500 }), 1500);
});

test("shouldCheck: 오프라인이면 안 함, 15초 안에는 반복하지 않음, 첫 확인은 통과", () => {
  assert.equal(shouldCheck({ now: T0, lastCheckAt: 0 }), true);
  assert.equal(shouldCheck({ now: T0, lastCheckAt: T0 - 14_999 }), false);
  assert.equal(shouldCheck({ now: T0, lastCheckAt: T0 - 15_000 }), true);
  assert.equal(shouldCheck({ now: T0, lastCheckAt: 0, online: false }), false);
  assert.equal(shouldCheck({ now: T0, lastCheckAt: T0, force: true }), true);
  assert.equal(shouldCheck({ now: T0, lastCheckAt: T0, force: true, online: false }), false, "강제라도 오프라인이면 안 함");
});

test("확인 계기가 폭주해도(포커스·표시 전환) 허용 간격당 한 번만 통과", () => {
  let last = 0, passed = 0;
  for (let t = 0; t < 60_000; t += 500) { if (shouldCheck({ now: T0 + t, lastCheckAt: last })) { last = T0 + t; passed += 1; } }
  assert.equal(passed, 4, "60초 동안 15초 간격으로 4번");
});

test("checkWaitMs: 막힌 확인 계기는 허용 간격이 지난 뒤로 미룸", () => {
  assert.equal(checkWaitMs({ now: T0, lastCheckAt: 0 }), 0);
  assert.equal(checkWaitMs({ now: T0, lastCheckAt: T0 - 4_000 }), 11_000);
  assert.equal(checkWaitMs({ now: T0, lastCheckAt: T0 }), 15_000);
  assert.equal(checkWaitMs({ now: T0, lastCheckAt: T0 - 20_000 }), 0);
  assert.equal(checkWaitMs({ now: T0, lastCheckAt: T0 - 5_000, minGapMs: 8_000 }), 3_000);
});

// ───────────── 미루기·안내 띠 ─────────────
test("snooze: 5분 뒤 다시 안내", () => {
  const until = snoozeUntil(T0);
  assert.equal(until, T0 + 5 * 60_000);
  assert.equal(isSnoozed(until, T0 + 1), true);
  assert.equal(isSnoozed(until, until - 1), true);
  assert.equal(isSnoozed(until, until), false);
  assert.equal(isSnoozed(0, T0), false);
  assert.equal(isSnoozed(undefined, T0), false);
});

test("shouldShowBanner: 업데이트가 있고 미루는 중·발표 중이 아닐 때만", () => {
  assert.equal(shouldShowBanner({ available: true, now: T0 }), true);
  assert.equal(shouldShowBanner({ available: false, now: T0 }), false);
  assert.equal(shouldShowBanner({ available: true, now: T0, snoozedUntil: T0 + 1000 }), false);
  assert.equal(shouldShowBanner({ available: true, now: T0, snoozedUntil: T0 - 1 }), true);
  assert.equal(shouldShowBanner({ available: true, now: T0, presenting: true }), false);
});

// ───────────── 자동 적용 ─────────────
const base = (o = {}) => ({
  available: true, now: T0, shownAt: T0, lastInteractionAt: 0, snoozedUntil: 0, autoAllowed: true,
  hasWork: true, persistOk: true, typing: false, dragging: false, busy: false, presenting: false, tutorial: false, saving: false, ...o,
});

test("unsafeReason: 입력·끌기·처리·발표·안내·저장·저장불가", () => {
  assert.equal(unsafeReason(base()), null);
  assert.equal(unsafeReason(base({ typing: true })), "typing");
  assert.equal(unsafeReason(base({ dragging: true })), "dragging");
  assert.equal(unsafeReason(base({ busy: true })), "busy");
  assert.equal(unsafeReason(base({ presenting: true })), "presenting");
  assert.equal(unsafeReason(base({ tutorial: true })), "tutorial");
  assert.equal(unsafeReason(base({ saving: true })), "saving");
  assert.equal(unsafeReason(base({ persistOk: false })), "no-persist");
  assert.equal(unsafeReason(base({ persistOk: false, hasWork: false })), null, "잃을 작업이 없으면 저장 가능 여부는 상관없음");
});

test("canAutoApply: 작업 중에는 마지막 조작 뒤 10초 조용해야 적용", () => {
  const at = ms => canAutoApply(base({ now: T0 + ms }));
  assert.deepEqual(at(0), { ok: false, reason: "wait", remainingMs: 10_000 });
  assert.deepEqual(at(9_999), { ok: false, reason: "wait", remainingMs: 1 });
  assert.deepEqual(at(10_000), { ok: true, reason: null, remainingMs: 0 });
});

test("canAutoApply: 조작하면 카운트다운이 처음부터", () => {
  const s = base({ now: T0 + 9_000, lastInteractionAt: T0 + 8_500 });
  assert.equal(canAutoApply(s).ok, false);
  assert.equal(canAutoApply(s).remainingMs, 9_500);
  assert.equal(canAutoApply({ ...s, now: T0 + 18_500 }).ok, true);
});

test("canAutoApply: 작업이 없으면(불러온 데이터 없음) 1.5초 만에 적용", () => {
  assert.equal(canAutoApply(base({ hasWork: false, now: T0 + 1_499 })).ok, false);
  assert.equal(canAutoApply(base({ hasWork: false, now: T0 + 1_500 })).ok, true);
});

test("canAutoApply: 글 입력·끌기·처리 중·발표 중이면 시간이 지나도 적용 안 함", () => {
  const late = T0 + 600_000;
  for (const flag of ["typing", "dragging", "busy", "presenting", "tutorial", "saving"]) {
    const d = canAutoApply(base({ now: late, [flag]: true }));
    assert.equal(d.ok, false, flag);
    assert.equal(d.reason, flag);
  }
  assert.equal(canAutoApply(base({ now: late })).ok, true, "다 끝나면 곧바로 적용");
});

test("canAutoApply: 작업 저장 불가 환경은 자동 적용 안 함(직접 누르는 것만)", () => {
  const d = canAutoApply(base({ now: T0 + 600_000, persistOk: false }));
  assert.deepEqual([d.ok, d.reason], [false, "no-persist"]);
});

test("canAutoApply: 미루는 중·반복 방지·업데이트 없음", () => {
  assert.equal(canAutoApply(base({ now: T0 + 60_000, snoozedUntil: T0 + 300_000 })).reason, "snoozed");
  assert.equal(canAutoApply(base({ now: T0 + 60_000, autoAllowed: false })).reason, "loop-guard");
  assert.equal(canAutoApply(base({ now: T0 + 60_000, available: false })).reason, "none");
});

test("canAutoApply: 미루기가 끝난 뒤에는 새 카운트다운(shownAt 갱신)으로 다시 진행", () => {
  const snoozeEnd = T0 + 300_000;
  const s = base({ shownAt: snoozeEnd, now: snoozeEnd + 3_000, snoozedUntil: snoozeEnd });
  assert.deepEqual([canAutoApply(s).ok, canAutoApply(s).remainingMs], [false, 7_000]);
});

test("canAutoApply: 시험용으로 대기 시간 조정 가능", () => {
  assert.equal(canAutoApply(base({ now: T0 + 2_000 }), { idleMs: 2_000 }).ok, true);
});

// ───────────── 안내 문구 ─────────────
test("bannerCopy: 작업 중 안내에 버전·자동 저장·남은 초", () => {
  const c = bannerCopy({ phase: "available", version: "5.30.0", hasWork: true, persistOk: true, reason: "wait", remainingMs: 7_300 });
  assert.match(c.text, /새 버전 v5\.30\.0이\(가\) 나왔습니다\./);
  assert.match(c.text, /작업 내용은 자동 저장됩니다/);
  assert.equal(c.hint, "8초 뒤 자동 적용");
});

test("bannerCopy: 남은 시간은 올림, 최소 1초", () => {
  assert.equal(bannerCopy({ phase: "available", hasWork: true, persistOk: true, reason: "wait", remainingMs: 1 }).hint, "1초 뒤 자동 적용");
  assert.equal(bannerCopy({ phase: "available", hasWork: true, persistOk: true, reason: "wait", remainingMs: 0 }).hint, "1초 뒤 자동 적용");
});

test("bannerCopy: 입력 중이면 마치면 적용된다고 안내, 작업 없으면 저장 문구 생략", () => {
  const c = bannerCopy({ phase: "available", version: "5.30.0", hasWork: false, persistOk: false, reason: "typing" });
  assert.doesNotMatch(c.text, /저장/);
  assert.match(c.hint, /입력을 마치면/);
});

test("bannerCopy: 저장 불가 환경에서는 다시 올려야 한다고 경고", () => {
  const c = bannerCopy({ phase: "available", version: "5.30.0", hasWork: true, persistOk: false, reason: "no-persist" });
  assert.match(c.text, /다시 올려야/);
  assert.equal(c.hint, "");
});

test("bannerCopy: 적용 중·실패, 버전 모를 때", () => {
  assert.match(bannerCopy({ phase: "applying", version: "5.30.0", hasWork: true, persistOk: true }).text, /v5\.30\.0 버전으로 업데이트하는 중/);
  assert.match(bannerCopy({ phase: "applying", hasWork: true, persistOk: true }).text, /새 버전으로 업데이트하는 중/);
  assert.match(bannerCopy({ phase: "failed", hasWork: true, persistOk: true }).text, /내려받지 못했습니다/);
  assert.match(bannerCopy({ phase: "available", hasWork: false, persistOk: true }).text, /^새 버전이 나왔습니다\./);
});

// ───────────── 새로고침 반복 방지 ─────────────
test("readGuard: 깨진 저장값은 빈 기록", () => {
  for (const raw of [null, "", "{", "[]", '{"entries":5}', '{"entries":[1,"a",{"at":"x"}]}']) assert.deepEqual(readGuard(raw), { entries: [] }, String(raw));
  assert.deepEqual(readGuard('{"entries":[{"at":5,"target":"a"},{"at":"x","target":"b"}]}'), { entries: [{ at: 5, target: "a" }] });
});

test("recordReload: 오래된 기록은 정리, 최대 8개", () => {
  let g = { entries: [] };
  g = recordReload(g, T0, "5.29.0#a");
  g = recordReload(g, T0 + 11 * 60_000, "5.30.0#b");
  assert.deepEqual(g.entries, [{ at: T0 + 11 * 60_000, target: "5.30.0#b" }], "10분 지난 기록은 제거");
  for (let i = 0; i < 20; i++) g = recordReload(g, T0 + 11 * 60_000 + i, `t${i}`);
  assert.equal(g.entries.length, 8);
});

test("autoReloadAllowed: 처음 보는 배포는 허용, 같은 배포로 방금 새로고침했으면 반복하지 않음(무한 새로고침 방지)", () => {
  let g = { entries: [] };
  assert.equal(autoReloadAllowed(g, T0, "5.29.0#a"), true);
  g = recordReload(g, T0, "5.29.0#a");
  assert.equal(autoReloadAllowed(g, T0 + 5_000, "5.29.0#a"), false, "새로고침 뒤에도 같은 배포가 감지됨 → 자동 반복 금지");
  assert.equal(autoReloadAllowed(g, T0 + 5_000, "5.30.0#b"), true, "그 사이 또 배포되어 다른 버전이면 허용");
  assert.equal(autoReloadAllowed(g, T0 + 11 * 60_000, "5.29.0#a"), true, "충분히 지나면 다시 시도 가능");
});

test("autoReloadAllowed: 짧은 기간(2분)의 총 횟수 상한 — 몇 분 간격의 연속 배포는 막지 않음", () => {
  let g = { entries: [] };
  for (let i = 0; i < DEFAULTS.maxReloadsInBurst; i++) g = recordReload(g, T0 + i * 1000, `v${i}`);
  assert.equal(autoReloadAllowed(g, T0 + 5_000, "새 배포"), false, "2분 안에 3번 새로고침했으면 중단");
  assert.equal(autoReloadAllowed(g, T0 + 2 * 60_000 + 2_001, "새 배포"), true, "2분이 지나면 다른 배포는 다시 허용");
  assert.equal(autoReloadAllowed(g, T0 + 2 * 60_000 + 2_001, "v0"), false, "같은 배포는 10분 동안 반복 금지");
  assert.equal(autoReloadAllowed(g, T0 + 11 * 60_000, "v0"), true);
  let slow = { entries: [] };
  for (let i = 0; i < 6; i++) slow = recordReload(slow, T0 + i * 3 * 60_000, `v${i}`);
  assert.equal(autoReloadAllowed(slow, T0 + 6 * 3 * 60_000, "v6"), true, "3분 간격으로 배포가 이어져도 계속 자동 적용");
});

test("autoReloadAllowed: 기록이 없거나 깨져도 안전", () => {
  assert.equal(autoReloadAllowed(undefined, T0, "x"), true);
  assert.equal(autoReloadAllowed(readGuard("깨짐"), T0, "x"), true);
});

// ───────────── 작업 복원 표식 ─────────────
test("parseResume: 유효한 표식·기한·형식", () => {
  const raw = JSON.stringify({ projectId: "p-abc", hash: "#/dash/사전", at: T0 });
  assert.deepEqual(parseResume(raw, T0 + 30_000), { projectId: "p-abc", hash: "#/dash/사전", at: T0 });
  assert.equal(parseResume(raw, T0 + 2 * 60_000 + 1), null, "2분 지나면 무효");
  assert.equal(parseResume(raw, T0 - 60_000), null, "미래 시각은 무효");
  assert.deepEqual(parseResume(JSON.stringify({ projectId: "p-1", hash: "javascript:x", at: T0 }), T0), { projectId: "p-1", hash: "", at: T0 }, "# 로 시작하지 않는 hash 는 버림");
  for (const bad of [null, "", "{", "[]", "{}", '{"projectId":"","at":1}', '{"projectId":5,"at":1}', `{"projectId":"p","at":"x"}`]) assert.equal(parseResume(bad, T0), null, String(bad));
});
